name: tvb

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Install unzip
        run: sudo apt-get install -y unzip

      - name: Download Chrome and ChromeDriver
        run: |
          # 下载 Chrome
          wget -N https://storage.googleapis.com/chrome-for-testing-public/132.0.6784.0/linux64/chrome-linux64.zip
          unzip chrome-linux64.zip
          sudo mv chrome-linux64 /opt/chrome

          # 下载 ChromeDriver
          wget -N https://storage.googleapis.com/chrome-for-testing-public/132.0.6784.0/linux64/chromedriver-linux64.zip
          unzip chromedriver-linux64.zip
          
          # 列出解压的文件
          ls chromedriver-linux64

          # 修改权限并移动 chromedriver
          chmod +x chromedriver-linux64/chromedriver
          sudo mv chromedriver-linux64/chromedriver /opt/chrome/chrome-linux64

      - name: Set Chrome Path
        run: echo "PATH=$PATH:/opt/chrome" >> $GITHUB_ENV

      - name: Install Python and Selenium
        run: |
          python -m pip install --upgrade pip
          pip install selenium

      - name: Run Selenium Script
        run: python ${{ github.workspace }}/取5个地区合并推送.py  # 替换为你的实际 Python 脚本
