name: Selenium Script

on:
  push:
    branches:
      - main

jobs:
  run-selenium:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2


      - name: Test file creation
        run: |
          mkdir test_directory
          touch test_directory/test_file.txt
          ls -l test_directory  # 列出目录内容以确认文件创建成功

      - name: Check URL accessibility
        run: |
          curl -I http://tonkiang.us/hoteliptv.php

