name: Python Selenium Script

on:
  push:
    branches:
      - main  # 或者你希望触发工作的其他分支
  workflow_dispatch:  # 允许手动触发工作流

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'  # 或其他你需要的Python版本

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Download Chrome and ChromeDriver
        run: |
          # 下载 Chrome
          wget -N https://storage.googleapis.com/chrome-for-testing-public/130.0.6723.58/linux64/chrome-linux64.zip
          unzip chrome-linux64.zip
          sudo mv chrome-linux64 /opt/chrome

          # 下载 ChromeDriver
          wget -N https://storage.googleapis.com/chrome-for-testing-public/130.0.6723.58/linux64/chromedriver-linux64.zip
          unzip chromedriver-linux64.zip
          chmod +x chromedriver
          sudo mv chromedriver /usr/local/bin/

      - name: Run Selenium Script
        run: |
          # 设置 Chrome 的路径
          export PATH=$PATH:/opt/chrome
          
          # 设置显示环境变量
          export DISPLAY=:99

          # 运行你的 Python 脚本
          python 取5个地区合并推送.py  # 将your_script.py替换为你的Python脚本文件名
