name: CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3  # Use the latest version

    - name: Set up Python
      uses: actions/setup-python@v4  # Use the latest version
      with:
        python-version: '3.8'  # Specify the desired Python version

    - name: Install dependencies
      run: |
        pip install -r requirements.txt

    - name: Run my script
      run: |
        python 测速.py
