name: CI

on:
  workflow_dispatch:  # 允许手动触发工作流
  push:
    branches:
      - main  # 代码推送到 main 分支时触发工作流

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11.7'

    - name: Install dependencies
      run: |
        pip install -r requirements.txt

    - name: Run my script
      run: |
        python 测速.py

    - name: Commit changes
      env:
        GITHUB_TOKEN: ${{ secrets.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 }}
      run: |
        git config --global user.name "Jassoon-cloud"
        git config --global user.email "youjason1235@gmail.com"
        git add .
        git commit -m "Update files" || echo "No changes to commit"
        git push https://x-access-token:${GITHUB_TOKEN}@github.com/Jassoon-cloud/TT.git HEAD:main
