name: CI

on:
  workflow_dispatch:  # 允许手动触发工作流
  push:
    branches:
      - main  # 代码推送到 main 分支时触发工作流

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3  # Use the latest version

    - name: Set up Python
      uses: actions/setup-python@v4  # Use the latest version
      with:
        python-version: '3.11.7'  # Specify the desired Python version

    - name: Install dependencies
      run: |
        pip install -r requirements.txt

    - name: Run my script
      run: |
        python 测速.py
